# 管理鉴定页自动生成的临时图片。
"""Temporary file helpers for identification screenshots."""

from __future__ import annotations

from pathlib import Path


IDENTIFY_CLIPBOARD_PREFIX = "identify_clipboard_"
IDENTIFY_CLIPBOARD_SUFFIX = ".png"


def iter_identify_clipboard_files(account_root: Path) -> list[Path]:
    """Return clipboard images generated by the app in the account root."""

    root = Path(account_root)
    if not root.exists():
        return []
    return sorted(
        path
        for path in root.glob(f"{IDENTIFY_CLIPBOARD_PREFIX}*{IDENTIFY_CLIPBOARD_SUFFIX}")
        if path.is_file()
    )


def is_identify_clipboard_file(path: Path, account_root: Path) -> bool:
    try:
        resolved = Path(path).resolve()
        root = Path(account_root).resolve()
    except Exception:
        return False
    return (
        resolved.parent == root
        and resolved.name.startswith(IDENTIFY_CLIPBOARD_PREFIX)
        and resolved.suffix.lower() == IDENTIFY_CLIPBOARD_SUFFIX
    )


def cleanup_identify_clipboard_files(paths: list[Path], account_root: Path) -> int:
    removed = 0
    for path in paths:
        if not is_identify_clipboard_file(path, account_root):
            continue
        try:
            Path(path).unlink(missing_ok=True)
            removed += 1
        except Exception:
            pass
    return removed
